fix for isort issue #104 and yamllint
alexcouper/captainhook pull request #114
Opened 2016-12-20 14:56 UTC by worroc

2017-03-07 14:58 UTC, OddBloke requested changes

2017-03-07 14:58 UTC, OddBloke commented on captainhook/checkers/yamllint_checker.py
> +                "`pip install yamllint` or turn it off in your {} file.".format(get_config_file()))
This line looks mis-indented (and long).

2017-03-07 14:58 UTC, OddBloke commented on captainhook/checkers/yamllint_checker.py
> +def _filter_yaml_files(files):
The comments indicate that this was copy/pasted; should we instead have this in `.utils` so both the Python, YAML and future checkers can use the same code path?

2017-03-07 15:52 UTC, OddBloke commented
(If you could split the isort change to a separate PR, that's easier to accept and would be much appreciated. :smile: )

2017-10-25 07:22 UTC, worroc commented
I will do all the staff in separate pull request

2017-10-25 07:22 UTC, closed without merging